version: '3.8'
services:
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  backend3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  lb:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - backend3
