version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  lb:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
